export const ADD_USER = 'ADD_USER_TO_USERS_LIST';
export const DELETE_USER = 'DELETE_USER_FROM_USERS_LIST';
export const UPDATE_USER = 'UPDATE_USER_FROM_USERS_LIST';

export const INCREMENT = 'COUNTER/INCREMENT';
export const DECREMENT = 'COUNTER/DECREMENT';
export const RESET = 'COUNTER/RESET';
